#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

export MUSL_INCLUDE="${MUSL_INCLUDE-/usr/local/lib}"

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
armv6l) ;&
armv7l) MACHTYPE=arm ;;
*) ;;
esac

export PDEATHSIGEXEC_CFLAGS="-no-pie"
export CC="musl-gcc -static -Os"
exec make $@
